Adding OAS support
TykTechnologies/tyk-sync pull request #74
Opened 2022-07-25 17:04 UTC by tbuchaillot

### Description
This PR adds OAS support. 

If an API has `is_oas` set to `true`, Tyk-sync will use `/api/apis/oas` endpoint to update the `id`. For the API creation, the normal `/api/apis` endpoint seems enough.

We fix the OAS ID modifying the `x-tyk-api-gateway.info.dbId` field with the new ID from API creation.

### How to test it
- Use tyk-sync dump command to dump OAS and tyk APIS
Example:
`./tyk-sync dump -d="http://localhost:3000" -s="7080fcd212a6489b64f6951f4b60e7b9" -t="examples/oas"`
It should dump all the APIs correctly.

- Manually delete all the APIs from the dashboard.
- Use tyk-sync sync command to re-create the APIs
Example:
`./tyk-sync sync -d="http://localhost:3000" -s="7080fcd212a6489b64f6951f4b60e7b9" -p="examples/oas" `
It should create the API's again.

- Use tky-sync sync command again. It should update the APIs instead of deleting and creating them again.

2022-07-26 16:33 UTC, sredxny requested changes

2022-07-26 16:33 UTC, sredxny commented on clients/dashboard/apis.go
> +		}
can we remove this?

2022-07-26 16:36 UTC, tbuchaillot commented on clients/dashboard/apis.go
> +		}
done @sredxny

2022-07-27 14:11 UTC, sredxny approved these changes
lgtm

2022-07-27 21:18 UTC, matiasinsaurralde approved these changes
Looks good, added just a small comment

2022-07-27 21:18 UTC, matiasinsaurralde commented on clients/dashboard/apis.go
> +	//fmt.Println(string(data))
Should we remove these lines?

2022-07-28 07:45 UTC, tbuchaillot commented on clients/dashboard/apis.go
> +	//fmt.Println(string(data))
whoooops, my bad 😅  removed

2022-07-28 14:26 UTC, tbuchaillot commented
@jeffy-mathew @furkansenharputlu  can any of you guys have a look?

2022-08-02 07:22 UTC, jeffy-mathew approved these changes

2022-08-02 07:26 UTC, merged

2022-08-02 07:26 UTC, tbuchaillot commented
/release to release-1.2