Docs/version
TykTechnologies/tyk-sync pull request #75
Opened 2022-08-02 07:34 UTC by tbuchaillot

Adding version command to Tyk Sync readme

2022-08-02 18:11 UTC, andyo-tyk requested changes

2022-08-02 18:11 UTC, andyo-tyk commented on README.md
> +  version     This command will show the current Tyk-Sync version.
For consistency, can you please delete the full stop `.`?

2022-08-02 18:11 UTC, andyo-tyk commented on README.md
> +## Example: Getting the current Tyk Sync version
Perhaps change this to:
`Example: Check the currently installed version of Tyk Sync`

2022-08-02 18:11 UTC, andyo-tyk commented on README.md
> +In order to get the current Tyk Sync version, we need to run the version command.
Please change this to say:
`To check the current Tyk Sync version, we need to run the version command:`

2022-08-03 07:45 UTC, tbuchaillot commented
Solved @andyo-tyk

2022-08-03 09:03 UTC, andyo-tyk approved these changes
Thanks!

2022-08-12 11:29 UTC, merged